# Generated by Django 2.0.3 on 2018-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180319_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='can_reserve_gender',
            field=models.IntegerField(choices=[(0, '不限'), (1, '仅限男性'), (2, '仅限女性')], default=0, help_text='对于未定义性别的用户只有不限性别选项可被预约', verbose_name='可预约性别'),
            preserve_default=False,
        ),
    ]
