# Generated by Django 2.0.3 on 2018-06-16 10:58

from django.db import migrations, models


def set_blank(apps, schema_editor):
    User = apps.get_model('account', 'User')
    UserInfo = apps.get_model('account', 'UserInfo')

    for u in User.objects.all():
        if u.name is None:
            u.name = ''
            u.save()

    for ui in UserInfo.objects.all():
        if ui.default_address is None:
            ui.default_address = ''
        if ui.intro is None:
            ui.intro = ''
        if ui.short_intro is None:
            ui.short_intro = ''
        ui.save()


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_auto_20180615_1714'),
    ]

    operations = [
        migrations.RunPython(set_blank),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='default_address',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='默认地点'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='intro',
            field=models.TextField(blank=True, default='', verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='short_intro',
            field=models.TextField(blank=True, default='', verbose_name='简介（显示于头像下方）'),
        ),
    ]
