# Generated by Django 2.0.3 on 2018-03-19 17:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatReserveTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='预约开始时间')),
                ('end_time', models.TimeField(verbose_name='预约结束时间')),
                ('repeat', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, '每周一'), (2, '每周二'), (3, '每周三'), (4, '每周四'), (5, '每周五'), (6, '每周六'), (7, '每周日')]), blank=True, help_text='重复选项，1-7 分别代表星期一至星期日重复，使用半角逗号分隔', null=True, size=7, verbose_name='重复选项')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('max', models.IntegerField(default=2, verbose_name='最大可预约人数')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('time_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('add_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('reservee', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='被预约人')),
            ],
            options={
                'verbose_name': '可预约时间（重复）',
                'verbose_name_plural': '可预约时间（重复）',
            },
        ),
        migrations.CreateModel(
            name='ReserveMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserver_mark', models.IntegerField(blank=True, choices=[(-1, '差评'), (0, '中评'), (1, '好评')], editable=False, null=True, verbose_name='预约人评分')),
                ('reserver_note', models.CharField(blank=True, editable=False, max_length=10000, null=True, verbose_name='预约人留言')),
                ('reserver_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='预约人评分时间')),
                ('reservee_mark', models.IntegerField(blank=True, choices=[(-1, '差评'), (0, '中评'), (1, '好评')], editable=False, null=True, verbose_name='被预约人评分')),
                ('reservee_note', models.CharField(blank=True, editable=False, max_length=10000, null=True, verbose_name='被预约人留言')),
                ('reservee_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='被预约人评分时间')),
            ],
            options={
                'verbose_name': '预约评分记录',
                'verbose_name_plural': '预约评分记录',
            },
        ),
        migrations.CreateModel(
            name='ReservePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='地点名称')),
                ('type', models.IntegerField(default=0, verbose_name='地点类型')),
                ('enabled', models.BooleanField(default=True, verbose_name='可选')),
            ],
            options={
                'verbose_name': '可选预约地点',
                'verbose_name_plural': '可选预约地点',
            },
        ),
        migrations.CreateModel(
            name='ReserveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容详情')),
                ('status', models.IntegerField(choices=[(-101, '预约人取消预约'), (-102, '被预约人取消预约'), (-103, '管理员取消预约'), (-104, '被预约人超时未答复自动取消预约'), (0, '预约已提交'), (100, '预约已确认'), (201, '预约已完成'), (202, '预约人未出席')], default=0, verbose_name='状态')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('time_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('add_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reserve.ReservePlace')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
            },
        ),
        migrations.CreateModel(
            name='ReserveTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.DateTimeField(verbose_name='预约开始时间')),
                ('end_time', models.DateTimeField(verbose_name='预约结束时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('ed', models.IntegerField(default=0, verbose_name='已预约人数')),
                ('max', models.IntegerField(default=2, verbose_name='最大可预约人数')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('time_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('add_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservetimelog', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('repeat', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.RepeatReserveTime', verbose_name='重复预约来源')),
                ('reservee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='被预约人')),
            ],
            options={
                'verbose_name': '可预约时间',
                'verbose_name_plural': '可预约时间',
            },
        ),
        migrations.CreateModel(
            name='ReserveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('hot', models.BooleanField(default=False, verbose_name='热搜')),
                ('order', models.IntegerField(default=999, verbose_name='排序')),
                ('type', models.IntegerField(choices=[(1, '课程辅导类'), (2, '非课程辅导类')], default=2, verbose_name='类别')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '可预约种类',
                'verbose_name_plural': '可预约种类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='confirm_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.ReserveTime', verbose_name='确认的预约时间'),
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='main_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reserve.ReserveTime', verbose_name='主预约时间'),
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='reserver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='预约人'),
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='time',
            field=models.ManyToManyField(related_name='_reserverecord_time_+', to='reserve.ReserveTime', verbose_name='预约时间'),
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='type',
            field=models.ManyToManyField(to='reserve.ReserveType', verbose_name='内容类别'),
        ),
        migrations.AddField(
            model_name='reservemark',
            name='record',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.ReserveRecord', verbose_name='预约记录'),
        ),
    ]
