# Generated by Django 2.0.3 on 2018-03-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservemark',
            name='record',
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='reservee_mark',
            field=models.IntegerField(blank=True, choices=[(-2, '差评'), (0, '中评'), (2, '好评')], editable=False, null=True, verbose_name='被预约人评分'),
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='reservee_mark_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='被预约人评分时间'),
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='reservee_note',
            field=models.CharField(blank=True, editable=False, max_length=10000, null=True, verbose_name='被预约人留言'),
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='reserver_mark',
            field=models.IntegerField(blank=True, choices=[(-2, '差评'), (0, '中评'), (2, '好评')], editable=False, null=True, verbose_name='预约人评分'),
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='reserver_mark_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='预约人评分时间'),
        ),
        migrations.AddField(
            model_name='reserverecord',
            name='reserver_note',
            field=models.CharField(blank=True, editable=False, max_length=10000, null=True, verbose_name='预约人留言'),
        ),
        migrations.AlterField(
            model_name='reserverecord',
            name='status',
            field=models.IntegerField(choices=[(-201, '预约人未出席'), (-101, '预约人取消预约'), (-102, '被预约人取消预约'), (-103, '管理员取消预约'), (-104, '被预约人超时未答复自动取消预约'), (0, '预约已提交'), (100, '预约已确认'), (201, '预约已完成')], default=0, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='ReserveMark',
        ),
    ]
