# Generated by Django 2.0.3 on 2018-03-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20180320_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserveplace',
            options={'ordering': ['type', 'name'], 'verbose_name': '可选预约地点', 'verbose_name_plural': '可选预约地点'},
        ),
        migrations.AlterModelOptions(
            name='reserverecord',
            options={},
        ),
        migrations.AlterField(
            model_name='repeatreservetime',
            name='reservee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='被预约人'),
        ),
        migrations.AlterField(
            model_name='reserveplace',
            name='type',
            field=models.IntegerField(choices=[(0, '任意'), (1, '仅限同性'), (2, '仅限异性'), (3, '仅限男男'), (4, '仅限女女')], default=0, verbose_name='地点类型'),
        ),
        migrations.AlterField(
            model_name='reserverecord',
            name='status',
            field=models.IntegerField(choices=[(-201, '预约人未出席'), (-101, '预约人取消预约'), (-102, '被预约人取消预约'), (-103, '管理员取消预约'), (-104, '被预约人超时未答复自动取消预约'), (0, '预约已提交'), (100, '预约已确认'), (200, '预约已完成')], default=0, verbose_name='状态'),
        ),
    ]
