# Generated by Django 2.0.3 on 2018-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='auth',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='权限'),
        ),
    ]
