# Generated by Django 2.0.3 on 2018-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='键')),
                ('value', models.CharField(max_length=80, verbose_name='值')),
                ('description', models.TextField(default='', verbose_name='说明')),
                ('order', models.IntegerField(default=99, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '全局设置',
                'verbose_name_plural': '全局设置',
            },
        ),
    ]
