# Generated by Django 2.0.3 on 2018-06-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('value', models.CharField(blank=True, default='', max_length=102400)),
            ],
            options={
                'verbose_name': '微信 SessionKey 存储',
                'verbose_name_plural': '微信 SessionKey 存储',
            },
        ),
        migrations.CreateModel(
            name='TemplateMessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=2048, verbose_name='模板 ID')),
                ('title', models.CharField(max_length=2048, verbose_name='模板标题')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '模板消息模板',
                'verbose_name_plural': '模板消息模板',
            },
        ),
        migrations.CreateModel(
            name='WechatConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('value', models.CharField(blank=True, default='', max_length=1024)),
                ('note', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '微信设置',
                'verbose_name_plural': '微信设置',
            },
        ),
    ]
