# Generated by Django 2.0.3 on 2018-06-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wechat', '0005_auto_20180615_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemessagetrigger',
            name='mini_program',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
