# Generated by Django 2.0.3 on 2018-06-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wechat', '0007_auto_20180616_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemessagetrigger',
            name='first_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='templatemessagetrigger',
            name='keyword1_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='templatemessagetrigger',
            name='keyword2_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='templatemessagetrigger',
            name='keyword3_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='templatemessagetrigger',
            name='keyword4_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='templatemessagetrigger',
            name='keyword5_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='templatemessagetrigger',
            name='keyword6_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='templatemessagetrigger',
            name='remark_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
