# Generated by Django 2.0.3 on 2018-06-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wechat', '0008_auto_20180616_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemessagetrigger',
            name='type',
            field=models.IntegerField(
                choices=[(-1, '未定义'), (201, 'TO预约人 - 预约提交成功'), (202, 'TO预约人 - 预约被拒绝'), (203, 'TO预约人 - 预约被取消'),
                         (204, 'TO预约人 - 预约被确认'), (205, 'TO预约人 - 预约已完成'), (206, 'TO预约人 - 预约被标记为无故未出席'),
                         (211, 'TO预约人 - 预约即将开始提醒'), (301, 'TO被预约人 - 收到预约'), (302, 'TO被预约人 - 预约未即时确认提醒'),
                         (303, 'TO被预约人 - 预约超时取消提醒'), (304, 'TO被预约人 - 预约完成提醒'), (311, 'TO被预约人 - 预约即将开始提醒')],
                verbose_name='类别'),
        ),
    ]
